# Generated by Django 4.1.1 on 2024-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
