# Generated by Django 5.0.1 on 2024-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ornek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('categories', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('read_more_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
