# Generated by Django 5.0.1 on 2024-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ornek', '0002_blogpost_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='C:/Users/beyzanur/Desktop/yazılımTesti_2/b201210100/static/assets/blog_images'),
        ),
    ]
