# Generated by Django 5.0.1 on 2024-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ornek', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='C:/Users/beyzanur/Desktop/yazılımTesti_2/b201210100/static/assets/industries_images')),
            ],
        ),
    ]
